/*
 * File: app/store/myViewStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('explorer.store.myViewStore', {
    extend: 'Ext.data.Store',

    requires: [
        'explorer.model.myViewModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'explorer.model.myViewModel',
            storeId: 'myViewStore',
            data: [
                {
                    Name: 'aspernatur',
                    Extension: '.txt',
                    //this is try out. For testing
                    Size: 14,
                    Date: '11/23/2005',
                    Owner: 'temporibus'
                },
                {
                    Name: 'nulla',
                    Extension: '.JPEG',
                    Size: 591,
                    Date: '11/3/2003',
                    Owner: 'necessitatibus'
                },
                {
                    Name: 'occaecati',
                    Extension: '.PSD',
                    Size: 582,
                    Date: '7/15/2012',
                    Owner: 'eos'
                },
                {
                    Name: 'fuga',
                    Extension: '.js',
                    Size: 138,
                    Date: '7/5/2011',
                    Owner: 'non'
                },
                {
                    Name: 'sed',
                    Extension: '.css',
                    Size: 609+'kb',
                    Date: '8/9/2008',
                    Owner: 'quisquam'
                },
                {
                    Name: 'consequatur',
                    Extension: '.html',
                    Size: 826,
                    Date: '3/1/2013',
                    Owner: 'praesentium'
                },
                {
                    Name: 'ut',
                    Extension: '.php',
                    Size: 241,
                    Date: '10/5/2012',
                    Owner: 'illum'
                },
                {
                    Name: 'exercitationem',
                    Extension: '.epub',
                    Size: 249,
                    Date: '12/26/2011',
                    Owner: 'aut'
                },
                {
                    Name: 'dolorem',
                    Extension: '.pdf',
                    Size: 254,
                    Date: '11/1/2003',
                    Owner: 'possimus'
                },
                {
                    Name: 'et',
                    Extension: '.dmg',
                    Size: 54,
                    Date: '10/28/2006',
                    Owner: 'perferendis'
                },
                {
                    Name: 'ea',
                    Extension: '.mp3',
                    Size: 144,
                    Date: '1/20/2002',
                    Owner: 'aliquid'
                },
                {
                    Name: 'sunt',
                    Extension: '.psd',
                    Size: 616,
                    Date: '4/2/2002',
                    Owner: 'molestias'
                },
                {
                    Name: 'et',
                    Extension: '.mov',
                    Size: 752,
                    Date: '4/9/2006',
                    Owner: 'incidunt'
                },
                {
                    Name: 'neque',
                    Extension: '.css',
                    Size: 626,
                    Date: '6/20/2007',
                    Owner: 'deleniti'
                },
                {
                    Name: 'soluta',
                    Extension: '.jpg',
                    Size: 635,
                    Date: '8/14/2007',
                    Owner: 'quae'
                },
                {
                    Name: 'omnis',
                    Extension: '.ttf',
                    Size: 497,
                    Date: '5/26/2014',
                    Owner: 'provident'
                },
                {
                    Name: 'qui',
                    Extension: '.sql',
                    Size: 318,
                    Date: '4/8/2011',
                    Owner: 'aut'
                },
                {
                    Name: 'sed',
                    Extension: '.iso',
                    Size: 628,
                    Date: '8/18/2002',
                    Owner: 'inventore'
                },
                {
                    Name: 'eaque',
                    Extension: '.Json',
                    Size: 125,
                    Date: '2/7/2006',
                    Owner: 'culpa'
                },
                {
                    Name: 'qui',
                    Extension: '.ajax',
                    Size: 670,
                    Date: '8/24/2013',
                    Owner: 'similique'
                },
                {
                    Name: 'autem',
                    Extension: '.js',
                    Size: 528,
                    Date: '3/15/2013',
                    Owner: 'tenetur'
                },
                {
                    Name: 'esse',
                    Extension: '.docx',
                    Size: 717,
                    Date: '11/15/2006',
                    Owner: 'ut'
                },
                {
                    Name: 'blanditiis',
                    Extension: '.xls',
                    Size: 107,
                    Date: '5/6/2002',
                    Owner: 'voluptatem'
                },
                {
                    Name: 'quia',
                    Extension: '.css',
                    Size: 74,
                    Date: '12/25/2012',
                    Owner: 'deleniti'
                },
                {
                    Name: 'eaque',
                    Extension: '.epub',
                    Size: 223,
                    Date: '7/23/2005',
                    Owner: 'non'
                },
                {
                    Name: 'aut',
                    Extension: '.html',
                    Size: 72,
                    Date: '6/1/2009',
                    Owner: 'dolorem'
                },
                {
                    Name: 'voluptas',
                    Extension: '.ttf',
                    Size: 132,
                    Date: '10/18/2001',
                    Owner: 'et'
                },
                {
                    Name: 'ad',
                    Extension: '.dwg',
                    Size: 536,
                    Date: '7/15/2003',
                    Owner: 'doloremque'
                },
                {
                    Name: 'ex',
                    Extension: '.php',
                    Size: 127,
                    Date: '8/18/2009',
                    Owner: 'sit'
                },
                {
                    Name: 'dolor',
                    Extension: '.iso',
                    Size: 426,
                    Date: '10/13/2011',
                    Owner: 'voluptas'
                },
                {
                    Name: 'Jesrel Agang',
                    //This is my Test fileSize for our Ext.util.Format
                    Extension: '.sms',
                    Size: 123456789,
                    Date: '1/22/2015',
                    Owner: 'Vhier.agang@gmail.com'//For example only!
                },
                {
                    Name: 'Jesrel Agang',
                    //This is my Test fileSize for our Ext.util.Format
                    Extension: '.dat',
                    Size: 123456789012345,
                    Date: '1/22/2015',
                    Owner: 'Vhier.agang@gmail.com'//For example only!
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});