/*
 * File: app/store/myViewStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('explorer.store.myViewStore', {
    extend: 'Ext.data.Store',

    requires: [
        'explorer.model.myViewModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'explorer.model.myViewModel',
            storeId: 'myViewStore',
            data: [
                {
                    Name: 'aspernatur',
                    Size: 14+'kb',
                    Date: '11/23/2005',
                    Owner: 'temporibus'
                },
                {
                    Name: 'nulla',
                    Size: 591+'kb',
                    Date: '11/3/2003',
                    Owner: 'necessitatibus'
                },
                {
                    Name: 'occaecati',
                    Size: 582+'kb',
                    Date: '7/15/2012',
                    Owner: 'eos'
                },
                {
                    Name: 'fuga',
                    Size: 138+'kb',
                    Date: '7/5/2011',
                    Owner: 'non'
                },
                {
                    Name: 'sed',
                    Size: 609+'kb',
                    Date: '8/9/2008',
                    Owner: 'quisquam'
                },
                {
                    Name: 'consequatur',
                    Size: 826+'kb',
                    Date: '3/1/2013',
                    Owner: 'praesentium'
                },
                {
                    Name: 'ut',
                    Size: 241+'kb',
                    Date: '10/5/2012',
                    Owner: 'illum'
                },
                {
                    Name: 'exercitationem',
                    Size: 249+'kb',
                    Date: '12/26/2011',
                    Owner: 'aut'
                },
                {
                    Name: 'dolorem',
                    Size: 254+'kb',
                    Date: '11/1/2003',
                    Owner: 'possimus'
                },
                {
                    Name: 'et',
                    Size: 54+'kb',
                    Date: '10/28/2006',
                    Owner: 'perferendis'
                },
                {
                    Name: 'ea',
                    Size: 144+'kb',
                    Date: '1/20/2002',
                    Owner: 'aliquid'
                },
                {
                    Name: 'sunt',
                    Size: 616+'kb',
                    Date: '4/2/2002',
                    Owner: 'molestias'
                },
                {
                    Name: 'et',
                    Size: 752+'kb',
                    Date: '4/9/2006',
                    Owner: 'incidunt'
                },
                {
                    Name: 'neque',
                    Size: 626+'kb',
                    Date: '6/20/2007',
                    Owner: 'deleniti'
                },
                {
                    Name: 'soluta',
                    Size: 635+'kb',
                    Date: '8/14/2007',
                    Owner: 'quae'
                },
                {
                    Name: 'omnis',
                    Size: 497+'kb',
                    Date: '5/26/2014',
                    Owner: 'provident'
                },
                {
                    Name: 'qui',
                    Size: 318+'kb',
                    Date: '4/8/2011',
                    Owner: 'aut'
                },
                {
                    Name: 'sed',
                    Size: 628+'kb',
                    Date: '8/18/2002',
                    Owner: 'inventore'
                },
                {
                    Name: 'eaque',
                    Size: 125+'kb',
                    Date: '2/7/2006',
                    Owner: 'culpa'
                },
                {
                    Name: 'qui',
                    Size: 670+'kb',
                    Date: '8/24/2013',
                    Owner: 'similique'
                },
                {
                    Name: 'autem',
                    Size: 528+'kb',
                    Date: '3/15/2013',
                    Owner: 'tenetur'
                },
                {
                    Name: 'esse',
                    Size: 717+'kb',
                    Date: '11/15/2006',
                    Owner: 'ut'
                },
                {
                    Name: 'blanditiis',
                    Size: 107+'kb',
                    Date: '5/6/2002',
                    Owner: 'voluptatem'
                },
                {
                    Name: 'quia',
                    Size: 74+'kb',
                    Date: '12/25/2012',
                    Owner: 'deleniti'
                },
                {
                    Name: 'eaque',
                    Size: 223+'kb',
                    Date: '7/23/2005',
                    Owner: 'non'
                },
                {
                    Name: 'aut',
                    Size: 72+'kb',
                    Date: '6/1/2009',
                    Owner: 'dolorem'
                },
                {
                    Name: 'voluptas',
                    Size: 132+'kb',
                    Date: '10/18/2001',
                    Owner: 'et'
                },
                {
                    Name: 'ad',
                    Size: 536+'kb',
                    Date: '7/15/2003',
                    Owner: 'doloremque'
                },
                {
                    Name: 'ex',
                    Size: 127+'kb',
                    Date: '8/18/2009',
                    Owner: 'sit'
                },
                {
                    Name: 'dolor',
                    Size: 426+'kb',
                    Date: '10/13/2011',
                    Owner: 'voluptas'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});