/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('explorer.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    itemId: 'headerPanel',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 231,
                    collapsed: true,
                    collapsible: true,
                    title: 'Project Folders',
                    titleCollapse: true,
                    store: 'MyTreeStore',
                    viewConfig: {
                        itemId: 'treeMenu'
                    }
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    layout: 'fit',
                    header: false,
                    title: 'Content',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            width: 150,
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            margin: '0 0 0 5',
                                            ui: 'plain',
                                            width: 35,
                                            iconCls: 'icon-backLogo'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            margin: '0 0 0 10',
                                            ui: 'plain',
                                            width: 35,
                                            iconCls: 'icon-forwardLogo'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            margin: '0 0 0 10',
                                            ui: 'plain',
                                            width: 35,
                                            iconCls: 'icon-reloadLogo '
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbseparator',
                                    margins: '0 0 0 50',
                                    height: 35,
                                    width: 3
                                },
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 28,
                                            margin: '0 0 0 50',
                                            ui: 'plain',
                                            width: 60,
                                            iconCls: 'icon-homeLogo',
                                            text: 'Home',
                                            textAlign: 'right'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 25,
                                            margin: '0 0 0 10',
                                            ui: 'plain',
                                            width: 60,
                                            href: '#',
                                            iconCls: 'icon-uploadLogo ',
                                            overflowText: 'Upload',
                                            text: 'Upload',
                                            textAlign: 'right'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 25,
                                            margin: '0 0 0 10',
                                            ui: 'plain',
                                            width: 75,
                                            iconCls: 'icon-downloadLogo',
                                            text: 'Download',
                                            textAlign: 'right'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 25,
                                            margin: '0 0 0 10',
                                            ui: 'plain',
                                            width: 25,
                                            href: '#',
                                            iconCls: 'icon-newFolderLogo'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 25,
                                            margin: '0 0 0 10',
                                            ui: 'plain-small',
                                            width: 25,
                                            iconCls: 'icon-folderDeleteLogo'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 23,
                                            margin: '0 0 0 10',
                                            ui: 'plain',
                                            width: 23,
                                            iconCls: 'icon-deleteLogo'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 0 215',
                                    width: 300,
                                    fieldLabel: 'Search',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'container',
                                    margin: '0 0 0 10',
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 23,
                                            ui: 'plain-small',
                                            width: 23,
                                            iconCls: 'icon-searchLogo'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'myViewStore'
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'mygridpanel',
                            header: false,
                            columnLines: true,
                            scroll: 'vertical',
                            store: 'myViewStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 360,
                                    dataIndex: 'Name',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    renderer: function(value) {
                                        return Ext.util.Format.fileSize(value);
                                    },
                                    sortable: true,
                                    dataIndex: 'Size',
                                    text: 'Size',
                                    format: '0,000'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 150,
                                    dataIndex: 'Date',
                                    text: 'Date Modified',
                                    format: 'Y/m/d'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 511,
                                    dataIndex: 'Owner',
                                    text: 'Owner'
                                }
                            ],
                            viewConfig: {
                                itemId: 'mygridview'
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});