/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xplorer.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    width: 200,
                    title: 'File',
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'treecolumn',
                            dataIndex: 'text',
                            text: 'Directory Tree',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Directory',
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            margins: '0 0 0 5',
                                                            height: 35,
                                                            ui: 'plain',
                                                            width: 75,
                                                            href: '#',
                                                            icon: 'icon-uploadLogo',
                                                            iconCls: 'icon-uploadLogo',
                                                            text: 'Upload',
                                                            textAlign: 'right',
                                                            tooltip: 'Upload'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            margins: '0 0 0 5',
                                                            height: 35,
                                                            itemId: 'download-Icon',
                                                            ui: 'plain',
                                                            width: 92,
                                                            href: '#',
                                                            iconCls: 'icon-downloadLogo',
                                                            text: 'Download',
                                                            textAlign: 'right',
                                                            tooltip: 'Download'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            margins: '0 0 0 5',
                                                            height: 35,
                                                            itemId: 'view-Icon',
                                                            ui: 'plain',
                                                            width: 63,
                                                            href: '#',
                                                            iconCls: 'icon-viewLogo',
                                                            text: 'View',
                                                            textAlign: 'right',
                                                            tooltip: 'View'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            margins: '0 0 0 5',
                                                            itemId: 'permission-Icon',
                                                            ui: 'plain',
                                                            width: 98,
                                                            href: '#',
                                                            iconCls: 'icon-permissionLogo',
                                                            text: 'Permission',
                                                            textAlign: 'right',
                                                            tooltip: 'Change Permission'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 598,
                                            title: '',
                                            store: 'propertyStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 250,
                                                    dataIndex: 'Name',
                                                    text: 'Name'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 130,
                                                    dataIndex: 'Size',
                                                    text: 'Size'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 130,
                                                    dataIndex: 'Type',
                                                    text: 'Type'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    width: 203,
                                                    dataIndex: 'Date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 250,
                                                    dataIndex: 'User',
                                                    text: 'User'
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'pagingtoolbar',
                                                    dock: 'bottom',
                                                    width: 360,
                                                    displayInfo: true,
                                                    store: 'propertyStore'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});