/*
 * File: app/model/myViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('explorer.model.myViewModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest',
        'Ext.data.writer.Json',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            name: 'Name',
            type: 'string'
        },
        {
            name: 'Size',
            type: 'int'
        },
        {
            name: 'Date',
            type: 'date'
        },
        {
            name: 'Owner',
            type: 'string'
        },
        {
            name: 'Extension',
            type: 'string'
        }
    ],

    proxy: {
        type: 'rest',
        url: '../comments',
        writer: {
            type: 'json',
            getData: function(data) {
                for(i = 0; i < data.length; i++){
                    data[i].createdTime = Ext.Date.format(new Date(data[i].createdTime), "Y-m-d");
                }
                return data;
            }
        },
        reader: {
            type: 'json'
        }
    }
});